# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-10-14 10:09:11

# Description: Prometheus is an open-source systems monitoring and alerting toolkit

version: '3'
services:
  prometheus:
    image: 'prom/prometheus'
    container_name: 'prometheus'
    hostname: 'prometheus-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:9090:9090'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus:/prometheus'
    networks:
      docker-network: {}
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'prometheus'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  prometheus:
    name: 'prometheus'


networks:
  docker-network:
    name: 'Docker-Network'
