# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2021-09-22 17:46:36

# Description: DataX离线数据同步工具/平台 —— web版

version: '2'
services:
  datax-web:
    image: 'happylay/datax-web:v2.1.1-standalone'
    container_name: 'datax-web'
    hostname: 'datax-web-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    depends_on:
      - 'datax-web-mysql'
    volumes:
      - '/etc/localtime:/etc/localtime'
      - './system/job:/job/json'
      - './system/jobhandler:/data/applogs/executor/jobhandler'
      - 'applogs:/data/applogs/admin'
    network_mode: "host"
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'datax-web'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'

  datax-web-mysql:
    image: 'happylay/mysql:5.7-v1.0.0'
    container_name: 'datax-web-mysql'
    hostname: 'datax-web-mysql-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    volumes:
      - '/etc/localtime:/etc/localtime'
      - 'mysql:/var/lib/mysql'
    network_mode: "host"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_USER: 'happylay'
      MYSQL_PASSWORD: 'happylay'
      MYSQL_DATABASE: 'datax_web'
      MYSQL_ROOT_PASSWORD: 'happylay'
    labels:
      servicename: 'datax-web-mysql'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  applogs:
    name: 'datax-web-log'
  mysql:
    name: 'datax-web-mysql'
