# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2022-05-10 15:25:11

# Description: Official build of Nginx

version: "3"
services:
  nginx:
    image: "nginx"
    container_name: "nginx"
    hostname: "nginx-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/conf.d:/etc/nginx/conf.d"
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/additional:/etc/nginx/additional"
      - "./config/sites-available:/etc/nginx/sites-available"
      - "./config/sites-enabled:/etc/nginx/sites-enabled"
      - "./config/dhparam.pem:/etc/nginx/dhparam.pem"
      - "./config/mime.types:/etc/nginx/mime.types"
      - "./certbot/etc/letsencrypt:/etc/letsencrypt"
      - "./certbot/var/lib/letsencrypt:/var/lib/letsencrypt"
      - "./www/MyServerName/public:/var/www/MyServerName/public"
      - "./log:/var/log/nginx"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
    labels:
      servicename: "nginx"
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

networks:
  docker-network:
    name: "Docker-Network"
