# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-06 11:09:34

# Description: Making Docker management easy. https://portainer.io

services:
  portainer:
    image: "portainer/portainer-ce"
    container_name: "portainer"
    hostname: "portainer-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - "0.0.0.0:8000:8000"
      - "127.0.0.1:9000:9000" # 8000 为 Agent 功能端口，9000 为HTTP端口，9443 为 HTTPS 端口
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer:/data"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
    labels:
      servicename: "portainer"
      com.centurylinklabs.watchtower.enable: false
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

volumes:
  portainer:
    name: "portainer"

networks:
  docker-network:
    name: "Docker-Network"
