# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-10-14 14:26:56

# Description: Chronograf is a visualization tool for time series data in InfluxDB

version: '3'
services:
  chronograf:
    image: 'chronograf'
    container_name: 'chronograf'
    hostname: 'chronograf-docker'
    restart: 'unless-stopped'       # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - 'chronograf:/var/lib/chronograf'
    networks:
      chronograf: {}
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'chronograf'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  chronograf:
    name: 'chronograf'
networks:
  chronograf:
    name: 'influxdata'
