# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2024-11-05 13:50:16

# Description: User-friendly AI Interface (Supports Ollama, OpenAI API, ...)

services:
  open-webui:
    image: "ghcr.io/open-webui/open-webui:main"
    container_name: "open-webui"
    hostname: "open-webui-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - "127.0.0.1:3000:8080"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "open-webui:/app/backend/data"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
      OLLAMA_BASE_URL: "http://ollama.local"
    labels:
      servicename: "open-webui"
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

volumes:
  open-webui:
    name: "open-webui"

networks:
  docker-network:
    name: "Docker-Network"

