# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2023-08-09 10:50:12

# Description: Web app for browsing, reading and downloading eBooks stored in a Calibre database

version: '3'
services:
  calibre-web:
    image: 'linuxserver/calibre-web'
    container_name: 'calibre-web'
    hostname: 'calibre-web-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '0.0.0.0:8083:8083'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './config:/config'
      - './books:/books'
    networks:
      docker-network: {}
    environment:
      TZ: 'Asia/Shanghai'
      PUID: 1000
      PGID: 1000
    labels:
      servicename: 'calibre-web'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


networks:
  docker-network:
    name: 'Docker-Network'
