# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-06-20 16:52:48

# Description: Docker Base image for Arch Linux

services:
  archlinux:
    image: "archlinux"
    container_name: "archlinux"
    hostname: "archlinux-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    stdin_open: true
    tty: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./resource/pacman.conf:/etc/pacman.conf"
      - "./resource/mirrorlist:/etc/pacman.d/mirrorlist"
      - "./resource/archlinuxcn-mirrorlist:/etc/pacman.d/archlinuxcn-mirrorlist"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
    labels:
      servicename: "archlinux"
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

networks:
  docker-network:
    name: "Docker-Network"
