# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2021-08-16 15:35:01

# Description:

version: '3'
services:
  node-red:
    image: 'nodered/node-red'
    container_name: 'node-red'
    hostname: 'node-red-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:1880:1880'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'node-red:/data'
    networks:
      node-red: {}
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'node-red'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  node-red:
    name: 'node-red'


networks:
  node-red:
    name: 'node-red'
