# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-11-04 14:30:32

# Description: Hello World

version: '3'
services:
  helloworld:
    image: 'hello-world'
    container_name: 'helloworld'
    hostname: 'helloworld-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    volumes:
      - '/etc/localtime:/etc/localtime'
    networks:
      helloworld: {}
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'helloworld'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


networks:
  helloworld:
    name: 'helloworld'
