# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2021-11-26 09:28:51

# Description: mrdoc的docker版本,支持arm64/amd64/armv7

version: '3'
services:
  mrdoc:
    image: 'jonnyan404/mrdoc-alpine'
    container_name: 'mrdoc'
    hostname: 'mrdoc-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:10086:10086'
    volumes:
      - '/etc/localtime:/etc/localtime'
      - 'mrdoc-config:/app/MrDoc/config'
      - 'mrdoc-media:/app/MrDoc/media'
    networks:
      mrdoc: {}
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'mrdoc'
      com.centurylinklabs.watchtower.enable: true
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  mrdoc-config:
    name: 'mrdoc-config'
  mrdoc-media:
    name: 'mrdoc-media'


networks:
  mrdoc:
    name: 'mrdoc'
