# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2021-11-26 09:28:51

# Description: mrdoc 的 docker 版本,支持 arm64/amd64/armv7

services:
  mrdoc:
    image: "zmister/mrdoc:v4"
    container_name: "mrdoc"
    hostname: "mrdoc-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - "127.0.0.1:10086:10086"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./source/MrDoc:/app/MrDoc"
      - "./config:/app/MrDoc/config"
      - "./media:/app/MrDoc/media"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
    labels:
      servicename: "mrdoc"
      com.centurylinklabs.watchtower.enable: true
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

networks:
  docker-network:
    name: "Docker-Network"
