# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2024-07-02 15:24:56

# Description: Docker image for running an Apache WebDAV server

services:
  webdav:
    image: "bytemark/webdav"
    container_name: "webdav"
    hostname: "webdav-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "$PWD/user.passwd:/user.passwd"   # WebDAV 用户密码文件
      - "/TODO:/var/lib/dav"              # WebDAV 基本目录
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
      LOCATION: "/webdav"
      AUTH_TYPE: "Digest"     # Basic（HTTPS 推荐使用）, Digest（HTTP 推荐使用）
      USERNAME: "username"
      PASSWORD: "password"
    labels:
      servicename: "webdav"
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

networks:
  docker-network:
    name: "Docker-Network"
