# File: docker-compose_https.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-04-29 14:34:46

# Description: GitLab Community Edition docker image based on the Omnibus package

# 需要几分钟进行初始化和健康检查
# 第一次运行不确定能否通过检测时最好去掉`-d`参数
# ---------------------------------------------- #
# gitlab image已经预置了用到的服务，包括:
#   nginx
#   redis
#   postgresql
#   ContainerRegistry
#   ......
# ---------------------------------------------- #

version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce'
    container_name: 'gitlab'
    hostname: 'gitlab-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '22:22'       # SSH
      - '80:80'       # HTTP
      - '443:443'     # HTTPS
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './config:/etc/gitlab'
      - 'data:/var/opt/gitlab'
      - 'logs:/var/log/gitlab'
    networks:
      gitlab: {}
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://127.0.0.1'              # 外部访问地址（HTTP或HTTPS，使用默认端口则不用加端口）
        letsencrypt['enable'] = false                 # 是否使用Let‘s Encrypt证书
        nginx['enable'] = true                        # 是否启用GitLab内部Nginx
        nginx['listen_port'] = 80                     # Nginx监听端口
        nginx['redirect_http_to_https'] = true        # 是否为GitLab启用HTTP到HTTPS重定向
        nginx['redirect_http_to_https_port'] = 80     # 重定向的端口
        nginx['ssl_certificate'] = '/etc/gitlab/ssl/gitlab.crt'
        nginx['ssl_certificate_key'] = '/etc/gitlab/ssl/gitlab.key'
        gitlab_rails['registry_enabled'] = false      # 不使用Container Registry
        high_availability['mountpoint'] = ['/etc/gitlab', '/var/opt/gitlab', '/var/log/gitlab']
    labels:
      servicename: 'gitlab'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  config:
    name: 'gitlab-config'
  data:
    name: 'gitlab-data'
  logs:
    name: 'gitlab-logs'


networks:
  gitlab:
    name: 'gitlab'
