# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-04-29 14:34:46

# Description: GitLab Community Edition docker image based on the Omnibus package

# 需要几分钟进行初始化和健康检查
# 第一次运行不确定能否通过检测时最好去掉`-d`参数
# ---------------------------------------------- #
# gitlab image已经预置了用到的服务，包括:
#   nginx
#   redis
#   postgresql
#   ContainerRegistry
#   ......
# ---------------------------------------------- #

version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce'
    container_name: 'gitlab'
    hostname: 'gitlab-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '22:22'       # SSH
      - '80:80'       # HTTP
      - '443:443'     # HTTPS
      - '5005:5005'   # Container Registry
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'config:/etc/gitlab'
      - 'data:/var/opt/gitlab'
      - 'logs:/var/log/gitlab'
    networks:
      gitlab: {}
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        high_availability['mountpoint'] = ['/etc/gitlab', '/var/opt/gitlab', '/var/log/gitlab']
        external_url 'http://127.0.0.1'               # 外部访问地址（HTTP或HTTPS，使用默认端口则不用加端口）
        nginx['enable'] = true                        # 是否启用GitLab内部Nginx
        nginx['listen_addresses'] = ['0.0.0.0']       # Nginx监听地址
        nginx['listen_port'] = 80                     # Nginx监听端口
        nginx['http2_enabled'] = true                 # 启用HTTP2
        nginx['client_max_body_size'] = '250m'        # 设置请求体最大体积
        nginx['redirect_http_to_https'] = true        # 为GitLab启用HTTP到HTTPS重定向
    labels:
      servicename: 'gitlab'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  config:
    name: 'gitlab-config'
  data:
    name: 'gitlab-data'
  logs:
    name: 'gitlab-logs'


networks:
  gitlab:
    name: 'gitlab'
