# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-04-29 14:34:46

# Description: GitLab Community Edition docker image based on the Omnibus package

# 需要几分钟进行初始化和健康检查
# 第一次运行不确定能否通过检测时最好去掉`-d`参数
# ---------------------------------------------- #
# gitlab image已经预置了用到的服务，包括:
#   nginx
#   redis
#   postgresql
#   ContainerRegistry
#   ......
# ---------------------------------------------- #
# GITLAB_OMNIBUS_CONFIG: |
#   external_url                外部访问的URL
#   letsencrypt['enable']       是否使用Let's Encrypt证书

version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce'
    container_name: 'gitlab'
    hostname: 'gitlab-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:22:22'       # SSH
      - '127.0.0.1:80:80'       # HTTP
      - '127.0.0.1:443:443'     # HTTPS
      - '127.0.0.1:5005:5005'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'config:/etc/gitlab'
      - 'data:/var/opt/gitlab'
      - 'logs:/var/log/gitlab'
    networks:
      gitlab: {}
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'gitlab'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  config:
    name: 'gitlab-config'
  data:
    name: 'gitlab-data'
  logs:
    name: 'gitlab-logs'


networks:
  gitlab:
    name: 'gitlab'
