# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-06-20 17:22:55

# Description: Official Docker images for the machine learning framework TensorFlow (http://www.tensorflow.org)

version: '3'
services:
  tensorflow:
    image: 'tensorflow/tensorflow'
    container_name: 'tensorflow'
    hostname: 'tensorflow-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    stdin_open: true
    tty: true
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      tensorflow: {}
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'tensorflow'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


networks:
  tensorflow:
    name: 'tensorflow'
