# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-10-14 14:32:04

# Description: The official Grafana docker container

services:
  grafana:
    image: "grafana/grafana"
    container_name: "grafana"
    hostname: "grafana-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "grafana:/var/lib/grafana"
      - "./plugins:/var/lib/grafana/plugins"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
      GF_PANELS_DISABLE_SANITIZE_HTML: true
    labels:
      servicename: "grafana"
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

volumes:
  grafana:
    name: "grafana"

networks:
  docker-network:
    name: "Docker-Network"
