# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-05-06 14:15:59

# Description: Redis is an open source key-value store that functions as a data structure server

version: '3'
services:
  redis:
    image: 'redis'
    container_name: 'redis'
    hostname: 'redis-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - '/etc/localtime:/etc/localtime'
      - 'redis:/data'
    networks:
      redis: {}
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'redis'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  redis:
    name: 'redis'


networks:
  redis:
    name: 'redis'
