# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2023-07-30 12:34:12

# Description: The Free Software Media Browser
#
# nyanmisaka/jellyfin是jellyfin成员针对中国用户特制版，开箱即用

services:
  jellyfin:
    image: "nyanmisaka/jellyfin"
    container_name: "jellyfin"
    hostname: "jellyfin-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - "0.0.0.0:8096:8096"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./cache:/cache"
      - "./media:/media:ro"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
    labels:
      servicename: "jellyfin"
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

networks:
  docker-network:
    name: "Docker-Network"
