#!/usr/bin/env bash

: << !
Name: post-commit
Author: YJ
Email: yj1516268@outlook.com
Created Time: 2023-10-08 13:57:32

Description: Git 钩子，git commit 后获取 hash

Attentions:
-

Depends:
-
!

# 获取最新commit哈希值
commit_hash=$(git rev-parse --short HEAD)
# 获取系统类型信息
kernel=$(uname -s)

function successInfo() {
  echo -e "\x1b[35m-----\x1b[0m\x1b[36m最新commit哈希值已复制\x1b[0m\x1b[35m-----\x1b[0m"
}

# 复制哈希值到系统剪贴板（-n参数表示不换行）
case $kernel in
  Linux)
    case $XDG_SESSION_TYPE in
      x11)
        echo -n "$commit_hash" | xsel --clipboard --input
        successInfo
        ;;
      wayland)
        echo -n "$commit_hash" | wl-copy
        successInfo
        ;;
      *)
        echo "Unsupported $XDG_SESSION_TYPE"
        ;;
    esac
    ;;
  Darwin)
    echo -n "$commit_hash" | pbcopy
    successInfo
    ;;
  *)
    echo "Unsupported $kernel"
    ;;
esac
