# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2021-11-26 08:58:23

# Description: A process for automating Docker container base image updates
# https://containrrr.dev/watchtower

services:
  watchtower:
    image: "containrrr/watchtower"
    container_name: "watchtower"
    hostname: "watchtower-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 86400 # 镜像更新轮询 1 天
      WATCHTOWER_LABEL_ENABLE: true # 更新 com.centurylinklabs.watchtower.enable 标签设置为 true 的容器
    labels:
      servicename: "watchtower"
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

networks:
  docker-network:
    name: "Docker-Network"
