# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-07-29 14:13:44

# Description: InfluxDB is an open source time series database for recording metrics, events, and analytics

services:
  influxdb:
    image: "influxdb"
    container_name: "influxdb"
    hostname: "influxdb-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - "127.0.0.1:8086:8086"
      - "127.0.0.1:8089:8089/udp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "influxdb:/var/lib/influxdb"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
      INFLUXDB_UDP_ENABLED: 1
      INFLUXDB_DB: "influxdb"
      INFLUXDB_USER: "influxdb"
      INFLUXDB_USER_PASSWORD: "influxdb"
    labels:
      servicename: "influxdb"
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

volumes:
  influxdb:
    name: "influxdb"

networks:
  docker-network:
    name: "Docker-Network"
