# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2021-09-02 14:45:30

# Description: Docker image with installed PLV8 extension on PostgreSQL 17 and PostgreSQL 16
#
# 创建 PLV8 扩展：```CREATE EXTENSION plv8;```

services:
  postgres-plv8:
    image: "sibedge/postgres-plv8"
    container_name: "postgres-plv8"
    hostname: "postgres-plv8-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "postgres-plv8:/var/lib/postgresql/data"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
      POSTGRES_DB: "postgres" # 默认数据库名
      POSTGRES_USER: "postgres" # 默认用户名
      POSTGRES_PASSWORD: "postgres" # 默认密码
    labels:
      servicename: "postgres-plv8"
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

volumes:
  postgres-plv8:
    name: "postgres-plv8"

networks:
  docker-network:
    name: "Docker-Network"
