# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2021-09-02 14:45:30

# Description: Postgres 10 + plv8 v2.3.0

version: '3'
services:
  postgres-plv8:
    image: 'pyramation/postgres-plv8'
    container_name: 'postgres-plv8'
    hostname: 'postgres-plv8-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:5434:5432'
    volumes:
      - '/etc/localtime:/etc/localtime'
      - 'postgres-plv8:/var/lib/postgresql/data'
    networks:
      postgres-plv8: {}
    environment:
      TZ: 'Asia/Shanghai'
      POSTGRES_DB: 'postgres'       # 默认数据库名
      POSTGRES_USER: 'postgres'     # 默认用户名
      POSTGRES_PASSWORD: 'postgres' # 默认密码
    labels:
      servicename: 'postgres-plv8'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  postgres-plv8:
    name: 'postgres-plv8'


networks:
  postgres-plv8:
    name: 'postgres-plv8'
