# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2023-07-06 15:44:00

# Description: A lightweight, self-hosted memo hub. Open Source and Free forever

version: '3'
services:
  memos:
    image: 'neosmemo/memos:latest'
    container_name: 'memos'
    hostname: 'memos-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:5230:5230'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './memos:/var/opt/memos'
    networks:
      docker-network: {}
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'memos'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


networks:
  docker-network:
    name: 'Docker-Network'
