portainer/portainer     --- docker run -d --name=portainer -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer:/data --restart=unless-stopped portainer/portainer
redis                   --- docker run -d --name=redis -p 6379:6379 -v redis:/data --restart=unless-stopped redis
rabbitmq                --- docker run -d --name=rabbitmq -p 5672:5672 -p 15672:15672 --hostname=YJ-Arch -v rabbitmq:/var/lib/rabbitmq --restart=unless-stopped rabbitmq:management
yhyj/archlinux          --- docker run -it --name=archlinux --restart=unless-stopped yhyj/archlinux:2.0
