# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2019-04-29 14:42:53

# Description: Odoo (formerly known as OpenERP) is a suite of open-source business apps

version: '3'
services:
  odoo:
    image: 'odoo'
    container_name: 'odoo'
    hostname: 'odoo-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:8069:8069'
      - '127.0.0.1:8071:8071'
      - '127.0.0.1:8086:8086'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'odoo:/var/lib/odoo'
      - 'odoo-extra_addons:/mnt/extra-addons'
    networks:
      odoo-postgres: {}
    environment:
      TZ: 'Asia/Shanghai'
      HOST: 'db'
    labels:
      servicename: 'odoo'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'

  db:
    image: 'postgres'
    container_name: 'pg4odoo'
    hostname: 'pg4odoo-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - 'pg4odoo:/var/lib/postgres/data'
      - 'pg4odoo:/var/lib/postgresql/data'
    networks:
      odoo-postgres:
        aliases:
          - 'db'
    environment:
      POSTGRES_DB: 'postgres'    # 默认数据库名
      POSTGRES_USER: 'odoo'
      POSTGRES_PASSWORD: 'odoo'
    labels:
      servicename: 'pg4odoo'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


volumes:
  odoo:
    name: 'odoo'
  odoo-extra_addons:
    name: 'odoo-extra_addons'
  pg4odoo:
    name: 'pg4odoo'


networks:
  odoo-postgres:
    name: 'odoo-postgres'
