# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2020-09-08 09:46:42

# Description: 开启binfmt_misc支持

version: "3"
services:
  binfmt:
    image: "docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64"
    container_name: "binfmt"
    hostname: "binfmt-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
    labels:
      servicename: "binfmt"
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

networks:
  docker-network:
    name: "Docker-Network"
