# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2023-08-08 09:16:48

# Description: A fast reverse proxy to help you expose a local server behind a NAT or firewall to the internet (Server version).

services:
  frp:
    image: "snowdreamtech/frps"
    container_name: "frps"
    hostname: "frp-docker"
    restart: "unless-stopped" # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - "0.0.0.0:12000:12000" # frps 服务绑定的端口
      - "0.0.0.0:12000:12000/udp" # frps 服务 KCP 协议绑定的端口
      - "127.0.0.1:12060:12060" # frps 服务 Dashboard 绑定的端口
      - "0.0.0.0:12080:12080" # frps 服务 vhost 绑定的端口
      - "0.0.0.0:12443:12443" # frps 服务 vhost 绑定的端口
      - "0.0.0.0:15000-15010:15000-15010" # 允许代理绑定的服务端端口
      - "0.0.0.0:15000-15010:15000-15010/udp" # 允许代理绑定的服务端端口
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./conf/frps.ini:/etc/frp/frps.ini"
      - "./log/frps.log:/var/log/frp/frps.log"
    networks:
      docker-network: {}
    environment:
      TZ: "Asia/Shanghai"
    labels:
      servicename: "frp"
    logging:
      driver: "json-file" # none, local, json-file(default), ...
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}"
        labels: "servicename"

networks:
  docker-network:
    name: "Docker-Network"
