# File: docker-compose.yml
# Author: YJ
# Email: yj1516268@outlook.com
# Created Time: 2020-01-16 16:45:33

# Description: 人人影视web端
#
# - 解锁密码：123456

version: '3'
services:
  yyets:
    image: 'xinebf/yyets'
    container_name: 'yyets'
    hostname: 'yyets-docker'
    restart: 'unless-stopped'   # no, unless-stopped, always, on-failure:<max-retries>
    privileged: false
    ports:
      - '127.0.0.1:3001:3001'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '$HOME/Documents/AppCache/yyets:/opt/work/store'
    networks:
      docker-network: {}
    environment:
      TZ: 'Asia/Shanghai'
    labels:
      servicename: 'yyets'
    logging:
      driver: 'json-file'       # none, local, json-file(default), ...
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.Name}}/{{.ID}}/{{.ImageName}}/{{.ImageID}}'
        labels: 'servicename'


networks:
  docker-network:
    name: 'Docker-Network'
